version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nextauth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nextauth_user
      POSTGRES_PASSWORD: nextauth_password
      POSTGRES_DB: nextauth_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - nextauth_network

  # Opcional: Adminer para administrar la base de datos
  adminer:
    image: adminer:latest
    container_name: nextauth_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - nextauth_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  nextauth_network:
    driver: bridge
